version: '3'
name: Divulgit
services:
  mongodb:
    image: mongo:4.2.12
    container_name: mongo-db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=divulgit
      - MONGO_INITDB_ROOT_PASSWORD=divulgit123
    networks: 
      - mongo-compose-network
  divulgit:
    image: divulgit:0.0.2
    container_name: divulgit
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=divulgit
      - SPRING_DATA_MONGODB_PASSWORD=divulgit123
      - SPRING_DATA_MONGODB_DATABASE=divulgit
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_APPLICATION_NAME=divulgit
      - LOGGING_FILE=logs/divulgit.log
      - LOGGING_LEVEL_ORG_DIVULGIT=INFO
    restart: on-failure
    depends_on:
      - mongodb
    networks: 
      - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge